// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PathDebugVisualizers.VSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "PathDebugVisualizers.VSIX.4eea47f6-5d64-4676-a6cc-3ff7b2a23efa";
        public const string Name = "Path Debug Visualizers";
        public const string Description = @"Open files or directories from the debugger when a variable contains the path.";
        public const string Language = "en-US";
        public const string Version = "0.2";
        public const string Author = "Matt Lacey";
        public const string Tags = "";
    }
}
